# Generated by Django 5.1.15 on 2026-08-13 13:01

import core.media_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualpaymentdetail',
            name='proof_document',
            field=models.FileField(blank=True, upload_to=core.media_paths.private_payment_proof_upload_to),
        ),
    ]
