# Generated by Django 5.1.15 on 2026-09-14 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0003_tenant_foundation'),
        ('organizations', '0001_tenant_foundation'),
        ('payments', '0002_alter_manualpaymentdetail_proof_document'),
        ('products', '0003_churchhub_external_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['organization', 'status'], name='payments_pa_organiz_1d83a8_idx'),
        ),
    ]
