# Generated by Django 5.1.15 on 2026-09-14 20:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_chart_of_accounts_and_journal'),
        ('organizations', '0002_backfill_personal_orgs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCalendar',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_business_date', models.DateField()),
                ('timezone_name', models.CharField(default='Africa/Accra', max_length=64)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_calendar', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization__name'],
                'indexes': [models.Index(fields=['current_business_date'], name='ledger_busi_current_82eefa_idx')],
            },
        ),
        migrations.CreateModel(
            name='BusinessDay',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('trial_balance_debit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('trial_balance_credit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_ledger_business_days', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_business_days', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'business days',
                'ordering': ['-business_date', 'organization'],
                'indexes': [models.Index(fields=['organization', 'status'], name='ledger_busi_organiz_e58d09_idx'), models.Index(fields=['organization', 'business_date', 'status'], name='ledger_busi_organiz_3f2625_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'business_date'), name='uniq_ledger_business_day_org_date')],
            },
        ),
    ]
