from django.urls import path

from control_room.product_views import (
    ProductCreateView,
    ProductDetailView,
    ProductListView,
    ProductPricingListView,
    ProductPricingPlanCreateView,
    ProductPricingPlanDeleteView,
    ProductPricingPlanUpdateView,
    ProductUpdateView,
)
from control_room.user_views import (
    TeamAssignRoleView,
    TeamListView,
    TeamRemoveRoleView,
    TeamRevokeInviteView,
    TeamUserDetailView,
)
from control_room.views import (
    AnnouncementCreateView,
    AnnouncementDeleteView,
    AnnouncementListView,
    AnnouncementUpdateView,
    ChangeLogView,
    ContentHubView,
    DashboardView,
    FeatureFlagCreateView,
    FeatureFlagListView,
    FeatureFlagToggleView,
    FeatureFlagUpdateView,
    NavigationEditView,
    NavigationListView,
    RedirectCreateView,
    RedirectDeleteView,
    RedirectListView,
    RedirectUpdateView,
    SeedRunAllView,
    SeedRunView,
    SettingsView,
    SetupView,
    BrandKitView,
    BrandKitDownloadView,
    BrandKitZipView,
)

app_name = "control_room"

urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("settings/", SettingsView.as_view(), name="settings"),
    path("brand-kit/", BrandKitView.as_view(), name="brand_kit"),
    path("brand-kit/download/<slug:asset_key>/", BrandKitDownloadView.as_view(), name="brand_kit_download"),
    path("brand-kit/download-all.zip", BrandKitZipView.as_view(), name="brand_kit_zip"),
    path("team/", TeamListView.as_view(), name="team"),
    path("team/<uuid:pk>/", TeamUserDetailView.as_view(), name="team_user"),
    path("team/<uuid:pk>/assign-role/", TeamAssignRoleView.as_view(), name="team_assign_role"),
    path("team/<uuid:pk>/remove-role/<uuid:role_pk>/", TeamRemoveRoleView.as_view(), name="team_remove_role"),
    path("team/invites/<uuid:pk>/revoke/", TeamRevokeInviteView.as_view(), name="team_revoke_invite"),
    path("navigation/", NavigationListView.as_view(), name="navigation"),
    path("navigation/<uuid:pk>/", NavigationEditView.as_view(), name="navigation_edit"),
    path("redirects/", RedirectListView.as_view(), name="redirects"),
    path("redirects/new/", RedirectCreateView.as_view(), name="redirect_create"),
    path("redirects/<uuid:pk>/edit/", RedirectUpdateView.as_view(), name="redirect_edit"),
    path("redirects/<uuid:pk>/delete/", RedirectDeleteView.as_view(), name="redirect_delete"),
    path("announcements/", AnnouncementListView.as_view(), name="announcements"),
    path("announcements/new/", AnnouncementCreateView.as_view(), name="announcement_create"),
    path("announcements/<uuid:pk>/edit/", AnnouncementUpdateView.as_view(), name="announcement_edit"),
    path("announcements/<uuid:pk>/delete/", AnnouncementDeleteView.as_view(), name="announcement_delete"),
    path("flags/", FeatureFlagListView.as_view(), name="flags"),
    path("flags/new/", FeatureFlagCreateView.as_view(), name="flag_create"),
    path("flags/<uuid:pk>/edit/", FeatureFlagUpdateView.as_view(), name="flag_edit"),
    path("flags/<uuid:pk>/toggle/", FeatureFlagToggleView.as_view(), name="flag_toggle"),
    path("content/", ContentHubView.as_view(), name="content"),
    path("products/", ProductListView.as_view(), name="products"),
    path("products/new/", ProductCreateView.as_view(), name="product_create"),
    path("products/<uuid:pk>/", ProductDetailView.as_view(), name="product_detail"),
    path("products/<uuid:pk>/edit/", ProductUpdateView.as_view(), name="product_edit"),
    path("products/<uuid:pk>/pricing/", ProductPricingListView.as_view(), name="product_pricing"),
    path("products/<uuid:product_pk>/pricing/new/", ProductPricingPlanCreateView.as_view(), name="product_pricing_create"),
    path(
        "products/<uuid:product_pk>/pricing/<uuid:pk>/edit/",
        ProductPricingPlanUpdateView.as_view(),
        name="product_pricing_edit",
    ),
    path(
        "products/<uuid:product_pk>/pricing/<uuid:pk>/delete/",
        ProductPricingPlanDeleteView.as_view(),
        name="product_pricing_delete",
    ),
    path("setup/", SetupView.as_view(), name="setup"),
    path("setup/run/<slug:key>/", SeedRunView.as_view(), name="seed_run"),
    path("setup/run-all/", SeedRunAllView.as_view(), name="seed_run_all"),
    path("changelog/", ChangeLogView.as_view(), name="changelog"),
]
