# Generated by Django 5.1.15 on 2026-09-14 20:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_backfill_personal_orgs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_number', models.CharField(max_length=32)),
                ('client_type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group'), ('business', 'Business')], default='individual', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blacklisted', 'Blacklisted'), ('closed', 'Closed')], default='active', max_length=20)),
                ('display_name', models.CharField(max_length=200)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('other_names', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('national_id', models.CharField(blank=True, max_length=64)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='GH', max_length=2)),
                ('notes', models.TextField(blank=True)),
                ('external_reference', models.CharField(blank=True, max_length=64)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mfi_clients', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfi_clients', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization', 'client_number'],
                'indexes': [models.Index(fields=['organization', 'status'], name='clients_cli_organiz_bb5819_idx'), models.Index(fields=['organization', 'client_type'], name='clients_cli_organiz_fa3b72_idx'), models.Index(fields=['organization', 'phone'], name='clients_cli_organiz_e4c665_idx'), models.Index(fields=['organization', 'display_name'], name='clients_cli_organiz_510c5f_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'client_number'), name='uniq_mfi_client_org_number'), models.UniqueConstraint(condition=models.Q(('national_id', ''), _negated=True), fields=('organization', 'national_id'), name='uniq_mfi_client_org_national_id')],
            },
        ),
    ]
