# Generated by Django 5.1.15 on 2026-08-10 15:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailverificationtoken_role_usersecurityprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('password_changed', 'Password Changed'), ('password_reset_requested', 'Password Reset Requested'), ('password_reset_completed', 'Password Reset Completed'), ('email_verified', 'Email Verified'), ('email_verification_sent', 'Email Verification Sent'), ('mfa_enabled', 'MFA Enabled'), ('mfa_disabled', 'MFA Disabled'), ('mfa_challenge', 'MFA Challenge'), ('session_revoked', 'Session Revoked'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked'), ('permission_denied', 'Permission Denied'), ('role_assigned', 'Role Assigned'), ('role_removed', 'Role Removed'), ('demo_request_submitted', 'Demo Request Submitted'), ('demo_request_updated', 'Demo Request Updated'), ('product_created', 'Product Created'), ('product_updated', 'Product Updated')], max_length=40),
        ),
        migrations.CreateModel(
            name='StaffInvitation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('grant_staff_access', models.BooleanField(default=True, help_text='Allow access to Control Room / Operations when accepted.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('accepted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invitations', to='accounts.role')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
