#!/usr/bin/env bash
# Filesystem backup of user-uploaded media (includes private payment proofs).
# Usage: sudo bash deploy/scripts/backup-media.sh
#
# Backs up $APP_DIR/media into a timestamped tar.gz under $BACKUP_ROOT/media/.
# Does not back up staticfiles/ (regenerated by collectstatic).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib/backup-common.sh
. "$SCRIPT_DIR/lib/backup-common.sh"

require_command tar
require_command sha256sum

MEDIA_DIR="$APP_DIR/media"
if [[ ! -d "$MEDIA_DIR" ]]; then
    echo "Media directory not found: $MEDIA_DIR" >&2
    exit 1
fi

ensure_backup_layout

STAMP="$(timestamp_utc)"
DEST_DIR="$BACKUP_ROOT/media/$STAMP"
mkdir -p "$DEST_DIR"
chmod 700 "$DEST_DIR"

ARCHIVE="$DEST_DIR/media-${STAMP}.tar.gz"
MANIFEST="$DEST_DIR/manifest.json"

log_backup_event INFO "Starting media backup from $MEDIA_DIR"

tar -C "$APP_DIR" -czf "$ARCHIVE" media

if [[ ! -s "$ARCHIVE" ]]; then
    log_backup_event ERROR "Media backup archive is empty: $ARCHIVE"
    exit 1
fi

write_manifest_json "$MANIFEST" "media" "$ARCHIVE" ""
chmod 600 "$ARCHIVE" "$MANIFEST"

log_backup_event INFO "Media backup complete: $ARCHIVE ($(wc -c <"$ARCHIVE" | tr -d ' ') bytes)"
