# Generated by Django 5.1.15 on 2026-08-10 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0001_initial'),
        ('products', '0003_churchhub_external_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='pricing_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='products.pricingplan'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_ends_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
