# Generated by Django 5.1.15 on 2026-09-14 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0002_buyer_journey'),
        ('organizations', '0001_tenant_foundation'),
        ('products', '0003_churchhub_external_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='license',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'status'], name='customer_po_organiz_27e9c7_idx'),
        ),
        migrations.AddIndex(
            model_name='license',
            index=models.Index(fields=['organization', 'status'], name='customer_po_organiz_b83688_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['organization', 'status'], name='customer_po_organiz_985911_idx'),
        ),
    ]
