# Generated by Django 5.1.15 on 2026-09-14 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_portal', '0003_tenant_foundation'),
        ('organizations', '0002_backfill_personal_orgs'),
        ('products', '0003_churchhub_external_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdownload',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='portal_downloads', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='portalnotification',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='portal_notifications', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_tickets', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='customerdownload',
            index=models.Index(fields=['organization', 'is_active'], name='customer_po_organiz_b31e14_idx'),
        ),
        migrations.AddIndex(
            model_name='portalnotification',
            index=models.Index(fields=['organization', 'is_read'], name='customer_po_organiz_a2ca3c_idx'),
        ),
        migrations.AddIndex(
            model_name='portalnotification',
            index=models.Index(fields=['user', 'is_read'], name='customer_po_user_id_5b8bf4_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['organization', 'status'], name='customer_po_organiz_fb1c3c_idx'),
        ),
    ]
