# Generated by Django 5.1.15 on 2026-07-31 08:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('structure', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('singleton_key', models.CharField(default='default', editable=False, max_length=32, unique=True)),
                ('site_name', models.CharField(default='Enterprise Platform', max_length=120)),
                ('site_tagline', models.CharField(blank=True, default='Classic software for modern enterprise teams', max_length=255)),
                ('site_description', models.TextField(blank=True, default='Enterprise software platform for modern teams.')),
                ('default_seo_title', models.CharField(blank=True, default='Enterprise Platform', max_length=120)),
                ('seo_twitter_handle', models.CharField(blank=True, max_length=80)),
                ('seo_default_og_image', models.CharField(blank=True, default='/static/images/og-default.svg', max_length=255)),
                ('contact_email', models.EmailField(blank=True, default='contact@example.com', max_length=254)),
                ('support_email', models.EmailField(blank=True, default='support@example.com', max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('footer_copyright', models.CharField(blank=True, default='© Enterprise Platform. All rights reserved.', max_length=255)),
                ('header_cta_primary_label', models.CharField(blank=True, default='Start Free Trial', max_length=60)),
                ('header_cta_primary_url_name', models.CharField(blank=True, default='contact:form', max_length=120)),
                ('header_cta_secondary_label', models.CharField(blank=True, default='Request a Demo', max_length=60)),
                ('header_cta_secondary_url_name', models.CharField(blank=True, default='contact:form', max_length=120)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True, default='We are performing scheduled maintenance. Please check back shortly.')),
                ('demo_form_enabled', models.BooleanField(default=True)),
                ('newsletter_enabled', models.BooleanField(default=True)),
                ('partner_program_enabled', models.BooleanField(default=True)),
                ('public_registration_enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Platform settings',
                'verbose_name_plural': 'Platform settings',
            },
        ),
        migrations.CreateModel(
            name='RedirectRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_path', models.CharField(help_text='Path starting with /, e.g. /old-page/', max_length=255, unique=True)),
                ('to_path', models.CharField(blank=True, help_text='Absolute path, e.g. /new-page/', max_length=255)),
                ('to_url_name', models.CharField(blank=True, help_text='Django URL name (optional if to_path set)', max_length=120)),
                ('redirect_type', models.CharField(choices=[('301', 'Permanent (301)'), ('302', 'Temporary (302)')], default='301', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['from_path'],
            },
        ),
        migrations.CreateModel(
            name='SiteAnnouncement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('variant', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('link_url', models.URLField(blank=True)),
                ('link_label', models.CharField(blank=True, max_length=60)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('show_on_public', models.BooleanField(default=True)),
                ('show_on_portal', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ControlChangeLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=80)),
                ('action', models.CharField(max_length=40)),
                ('summary', models.CharField(max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='control_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
