# Generated by Django 5.1.15 on 2026-08-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='brand_accent_color',
            field=models.CharField(default='#c9a227', help_text='Accent brand color (hex), e.g. #c9a227', max_length=7),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='brand_primary_color',
            field=models.CharField(default='#1e3a5f', help_text='Primary brand color (hex), e.g. #1e3a5f', max_length=7),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='brand_theme_preset',
            field=models.CharField(default='navy_gold', help_text='Site color theme preset.', max_length=32),
        ),
    ]
