# Generated by Django 5.1.15 on 2026-08-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_room', '0005_sync_control_room_nav'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='social_linkedin_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='social_twitter_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='social_youtube_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='support_sla_hours',
            field=models.PositiveIntegerField(default=24, help_text='Target first-response time in business hours for support tickets.'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='brand_theme_preset',
            field=models.CharField(default='zreta_indigo', help_text='Site color theme preset.', max_length=32),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='header_cta_primary_url_name',
            field=models.CharField(blank=True, default='contact:trial', max_length=120),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='header_cta_secondary_url_name',
            field=models.CharField(blank=True, default='contact:demo', max_length=120),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='public_registration_enabled',
            field=models.BooleanField(default=True, help_text='Allow self-serve signup and free trials from pricing pages.'),
        ),
    ]
