# Generated by Django 5.1.15 on 2026-08-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_room', '0006_buyer_journey'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='brand_favicon',
            field=models.ImageField(blank=True, help_text='Optional favicon override (32×32 or 64×64 PNG/ICO/SVG).', null=True, upload_to='brand/'),
        ),
        migrations.AddField(
            model_name='platformsettings',
            name='brand_logo',
            field=models.ImageField(blank=True, help_text='Platform logo shown in header and portals (PNG/SVG/JPG, max 2MB recommended).', null=True, upload_to='brand/'),
        ),
    ]
