# Generated by Django 5.1.15 on 2026-08-10 18:41

import control_room.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_room', '0007_team_and_branding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='brand_favicon',
            field=models.FileField(blank=True, help_text='Optional favicon override (PNG, ICO, or SVG; 32×32 or 64×64 recommended).', null=True, upload_to='brand/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'gif', 'webp', 'svg', 'ico'], message='Upload a PNG, JPG, WEBP, SVG, or ICO file.'), control_room.validators.validate_brand_file_size]),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='brand_logo',
            field=models.FileField(blank=True, help_text='Platform logo shown in header and portals (PNG, JPG, WEBP, or SVG; max 2MB).', null=True, upload_to='brand/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'gif', 'webp', 'svg', 'ico'], message='Upload a PNG, JPG, WEBP, SVG, or ICO file.'), control_room.validators.validate_brand_file_size]),
        ),
    ]
