# Generated by Django 5.1.15 on 2026-08-12 01:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_room', '0009_sync_documentation_nav'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformOperationsSettings',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('singleton_key', models.CharField(default='default', editable=False, max_length=32, unique=True)),
                ('use_custom_smtp', models.BooleanField(default=False, help_text='When enabled, Control Room SMTP settings override environment email config.')),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('default_from_email', models.EmailField(blank=True, max_length=254)),
                ('last_email_test_at', models.DateTimeField(blank=True, null=True)),
                ('last_email_test_status', models.CharField(blank=True, max_length=32)),
                ('last_email_test_message', models.TextField(blank=True)),
                ('git_remote', models.CharField(default='origin', max_length=120)),
                ('git_branch', models.CharField(default='main', max_length=120)),
                ('last_deploy_at', models.DateTimeField(blank=True, null=True)),
                ('last_deploy_status', models.CharField(blank=True, max_length=32)),
                ('last_deploy_output', models.TextField(blank=True)),
                ('last_deploy_commit', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name': 'Platform operations settings',
                'verbose_name_plural': 'Platform operations settings',
                'permissions': [('manage_platform_operations', 'Can manage platform email and deploy settings')],
            },
        ),
    ]
