# Generated by Django 5.1.15 on 2026-08-14 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_room', '0011_platform_ops_nav_and_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='default_seo_title',
            field=models.CharField(blank=True, default='Zreta', max_length=120),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='footer_copyright',
            field=models.CharField(blank=True, default='© Zreta. All rights reserved.', max_length=255),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='site_description',
            field=models.TextField(blank=True, default='Modular enterprise software platform for faith, finance, education, healthcare, and operations.'),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='site_name',
            field=models.CharField(default='Zreta', max_length=120),
        ),
        migrations.AlterField(
            model_name='platformsettings',
            name='site_tagline',
            field=models.CharField(blank=True, default='Modular enterprise software for growing organizations', max_length=255),
        ),
    ]
