# Generated by Django 5.1.15 on 2026-07-30 23:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonAttribute',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('group', models.CharField(blank=True, help_text='Section heading in comparison table.', max_length=120)),
                ('value_type', models.CharField(choices=[('boolean', 'Yes / No'), ('text', 'Text')], default='boolean', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['group', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140)),
                ('description', models.TextField(blank=True)),
                ('billing_interval', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual'), ('one_time', 'One-time'), ('custom', 'Custom / Contact Sales')], default='monthly', max_length=20)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_contact_sales', models.BooleanField(default=False, help_text="When enabled, price displays as 'Contact Sales' instead of amount.")),
                ('is_published', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('short_description', models.TextField(blank=True)),
                ('long_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('coming_soon', 'Coming Soon'), ('beta', 'Beta'), ('ga', 'Generally Available'), ('deprecated', 'Deprecated')], default='draft', max_length=20)),
                ('accent', models.CharField(choices=[('churchhub', 'ChurchHub (Indigo)'), ('microfinance', 'Microfinance (Teal)'), ('erp', 'ERP (Blue)'), ('school', 'School (Purple)'), ('hospital', 'Hospital (Cyan)'), ('hr', 'HR & Payroll (Orange)'), ('default', 'Default (Primary Blue)')], default='default', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('external_app_url', models.URLField(blank=True)),
                ('documentation_url', models.URLField(blank=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, upload_to='products/heroes/')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'product category',
                'verbose_name_plural': 'product categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255)),
                ('is_included', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='products.pricingplan')),
            ],
            options={
                'ordering': ['sort_order', 'text'],
            },
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='products.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productcategory'),
        ),
        migrations.CreateModel(
            name='ProductDemoRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=120)),
                ('work_email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('closed', 'Closed')], default='new', max_length=20)),
                ('source', models.CharField(blank=True, default='website', max_length=80)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demo_requests', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductDownload',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='products/downloads/')),
                ('file_type', models.CharField(choices=[('brochure', 'Brochure'), ('datasheet', 'Datasheet'), ('whitepaper', 'Whitepaper'), ('case_study', 'Case Study'), ('other', 'Other')], default='brochure', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='products.product')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProductModule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='products.product')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('product', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_highlighted', models.BooleanField(default=False)),
                ('plans', models.ManyToManyField(blank=True, help_text='Plans that include this feature. Empty = all plans.', related_name='features', to='products.pricingplan')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='products.product')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='features', to='products.productmodule')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProductScreenshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='products/screenshots/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='products.product')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video_type', models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('external', 'External URL'), ('embed', 'Embed Code')], default='youtube', max_length=20)),
                ('video_url', models.URLField(blank=True)),
                ('embed_code', models.TextField(blank=True, help_text='Optional raw embed HTML.')),
                ('thumbnail', models.ImageField(blank=True, upload_to='products/video-thumbs/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='products.product')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('region', models.CharField(default='global', help_text='e.g. global, us, eu, africa', max_length=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_label', models.CharField(blank=True, help_text="Override display, e.g. 'Custom pricing'", max_length=80)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='products.pricingplan')),
            ],
            options={
                'ordering': ['region', 'currency'],
                'unique_together': {('plan', 'region', 'currency')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='pricingplan',
            unique_together={('product', 'slug')},
        ),
        migrations.CreateModel(
            name='ProductComparisonEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_text', models.CharField(blank=True, max_length=255)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='products.comparisonattribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_entries', to='products.product')),
            ],
            options={
                'unique_together': {('product', 'attribute')},
            },
        ),
    ]
