# Generated by Django 5.1.15 on 2026-08-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='demo_url',
            field=models.URLField(blank=True, help_text='External demo/inquiry form hosted by the product app, e.g. https://mychurch.zreta.com/contact/'),
        ),
        migrations.AddField(
            model_name='product',
            name='register_url',
            field=models.URLField(blank=True, help_text='External registration/onboarding URL, e.g. https://mychurch.zreta.com/apply/'),
        ),
        migrations.AddField(
            model_name='productscreenshot',
            name='kind',
            field=models.CharField(choices=[('screenshot', 'Screenshot'), ('template', 'Template preview')], default='screenshot', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='external_app_url',
            field=models.URLField(blank=True, help_text='Live product URL, e.g. https://app.zreta.com or https://mychurch.zreta.com/'),
        ),
    ]
